spring:
  config:
    activate:
      on-profile:
      - qa




build:
  version: "5.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Muhammet Celik - prod Developer"
    email: "muhammetclk56@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345