
spring:
  config:
    activate:
      on-profile:
      - prod




build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related PROD APIs "
  contactDetails:
    name: "Muhammet Celik - PROD Developer"
    email: "muhammetclk56@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345